import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from './providers';
import "./globals.css";
import Link from "next/link";
import nstyles from "./navbar.module.css";
import { EdgeStoreProvider } from '../lib/edgestore';
import { Button } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <Providers>
          <nav className={nstyles.navbar}>
            <Link href="/" passHref>
              <div className={`${nstyles.rightLinks}`}> <p>SRY</p> </div>
            </Link>
            <div className={`${nstyles.rightLinks}`}>
              <Link href="/" passHref>
                Page
              </Link>
              <Link href="/" passHref>
                Page
              </Link>
              <Link href="/" passHref>
                Page
              </Link>
              <button className={`${nstyles.button}`}>
                Submit
              </button>
            </div>
          </nav>
          {children}
          </Providers>
        </EdgeStoreProvider>
      
      </body>
    </html>
  );
}
